version: '2'
services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: iteloganalysis/kibana
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch

  logstash:
    image: iteloganalysis/logstash
    container_name: logstash
    ports:
      - 5044:5044
    links:
      - elasticsearch

  order_service:
    image: iteloganalysis/order-service
    container_name: order_service
    ports:
      - 8081:8081
    links:
      - logstash
      - elasticsearch
