version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.0
    container_name: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: iteloganalysis/log-analysis/kibana
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch

  logstash:
    image: iteloganalysis/log-analysis/logstash
    container_name: logstash
    links:
      - elasticsearch

  order_service:
    image: iteloganalysis/order-service
    ports:
      - 8081
    links:
      - logstash

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - order_service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
