elasticsearch:
  image: elasticsearch
  container_name: elasticsearch
  ports:
    - 9200:9200

kibana:
  image: iteloganalysis/kibana
  container_name: kibana
  ports:
    - 5601:5601
  links:
    - elasticsearch:elasticsearch

order_service:
  image: iteloganalysis/order-service
  container_name: order_service
  ports:
    - 8081:8081
  links:
    - elasticsearch:elasticsearch
