filebeat.prospectors:

- input_type: log

  paths:
    - "/var/log/*.log"

  document_type: error-log

  json.message_key: message
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  #pipeline: ""
  index: "filebeat-%{+yyyy.MM.dd}"
  template.enabled: true
  template.name: "filebeat"
  template.path: "${path.config}/filebeat.template.json"
  template.overwrite: false

  template.versions.2x.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  rotateeverybytes: 10485760
  keepfiles: 7
