# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#=========================== Filebeat prospectors =============================

filebeat:
  prospectors:
    -
      paths:
        - "/var/log/*.log"
      input_type: log
      multiline:
        pattern: '^[[:space:]]|(INFORMATION)'
        negate: false
        match: after

#================================ Outputs =====================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.
output:
#-------------------------- Elasticsearch output ------------------------------
  # elasticsearch:
  #   hosts: ["http://elasticsearch:9200"]
  #   index: "filebeat"
  #   template:
  #     path: "/etc/filebeat/filebeat.template.json"

#----------------------------- Logstash output --------------------------------
  logstash:
    hosts: ["logstash:5044"]
    index: filebeat

#================================ Logging =====================================

logging:
  level: warning
  to_syslog: false
  to_files: true
  files:
    path: /var/log/filebeat
    name: beat.log
